flows:
  - "auth/**/*.yaml"
  - "cards/**/*.yaml"
  - "checkout/*.yaml"
  - "settings/*.yaml"
executionOrder:
  continueOnFailure: true
  flowsOrder:
    - "LoginSuccess"
    - "LoginFailureInvalidOTP"
    - "LoginFailureIncorrectPasscode"
    - "ForgotPasscodeSuccess"
    - "SetPasscodePolicyViolationError"
    - "ShowVirtualCardDetailsSuccess"
    - "ShowVirtualCardDetailsFailure"
    - "ShowPhysicalCardDetailsSuccess"
    - "ShowPhysicalCardDetailsFailure"
    - "HideVirtualCardDetailsSuccess"
    - "HidePhysicalCardDetailsSuccess"
    - "FreezeUnfreezeVirtualCardSuccess"
    - "FreezeUnfreezePhysicalCardSuccess"
    - "VirtualCardAllowEcommerce"
    - "PhysicalCardAllowEcommerce"
    - "VirtualCardDailyLimitSuccess"
    - "PhysicalCardATMWithDrawlDailyLimitSuccess"
    - "VirtualCardMonthlyLimitSuccess"
    - "PhysicalCardATMWithDrawlMonthlyLimitSuccess"
    - "VirtualCardYearlyLimitSuccess"
    - "PhysicalCardATMWithDrawlYearlyLimitSuccess"
    - "PhysicalCardE-commAndPOSDailyLimitSuccess"
    - "PhysicalCardE-commAndPOSMonthlyLimitSuccess"
    - "PhysicalCardE-commAndPOSYearlyLimitSuccess"
    - "LoadFundsFromExistingCardSuccess"
    - "LoadFundsFromNewCardSuccess"
    - "LoadFundsFromExistingCardSuccess"
    - "LoadFundsExceededAmountError"
    - "LoadFundsInvalidCardDetailsError"
    - "ViewProfile"
    - "Logout"

# Test Output Configuration
# All test artifacts (screenshots, logs, reports, recordings) will be stored in this directory
# Path is relative to where the maestro command is executed from
testOutputDir: "ata/test-output"

# Platform Configuration
platform:
  ios:
    disableAnimations: true
  android:
    disableAnimations: true
